#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/root/script/qos_script.sh

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh $PROG start
    procd_set_param type oneshot
    procd_close_instance
}

stop_service() {
    /bin/sh $PROG stop
}

restart() {
    /bin/sh $PROG stop
    sleep 1
    /bin/sh $PROG start
}
